### PR TITLE
Bootstrap Custom URLs

### PR DESCRIPTION
**Pull request by ghost**
**Ok, sorry for all the edits. Freezing my progress so that you can actually take a look.**

To me, the easiest way to give the user an option on Bootstrap version is to give them access to the source URL.

I made custom URLs the default if not blank. This makes the most sense to me. That way a user could input anything for bootstrap CSS or JS, choose whether to disable them altogether and can use a default CDN, default plugin loaded files, or simply opt to type in their own URLs. Maybe add an option for custom bootstrap themes too? Otherwise, I'd say this case is closed.

This solution is flexible. You could do a mixture of one custom URL and one from the `plugin://` url. Or one custom URL and one from the default CDN. Before this PR, you were forced to do either ALL from the CDN or ALL from your own website, not a combination of both. Also, the user immediately gets the right to overwrite the location should they choose to input their own URL. Maybe this should be designated optional in case someone thinks they must type in a URL.

screen shot 2016-07-18 at 8 54 05 pm

### CODE REVIEW

**Comment by barryanders** [comment]
Ignore my request. I'm going to fix it and update with just one push.

**Comment by barryanders** [comment]
There's only one thing that may confuse the user right now:

If both CDN and Custom URLs are toggled on, then the plugin defaults to using the local files. It's a safety net, but it will confuse the user as they may not understand what is going on. Instead, if there was a way to force the two to be opposite of the other, that'd be great. So for example

If CDN is on, then Custom URL is off.
If custom URL is on, then CDN is off.

Otherwise, this is working.

**Comment by barryanders** [comment]
My first thought to solve the aforementioned problem was to make Custom URLs and CDN into a dropdown menu and also add local files as a third option, however, I thought it might be better to leave things the way they are and just make it so that if a custom URL is inputed, then it overwrites the default CDN in place. If no custom URLs are used, then the CDN acts as usual.

**Comment by barryanders** [comment]
One more edit. Simply making custom URLs the default if not blank. This makes the most sense to me. That way a user could input anything for bootstrap CSS or JS, choose whether to disable them altogether and can use a default CDN, default plugin loaded files, or simply opt to type in their own URLs. Maybe add an option for custom bootstrap themes too? Otherwise, I'd say this case is closed.

**Comment by flaviocopes** [comment]
Can we do this simply with a select box `Version: 3 / 4`, instead of having to manually enter the URL? So by updating the plugin you'll always get the latest bootstrap release

**Comment by ghost** [comment]
That's how I had it set up originally, but I personally liked the ability to enter the URL (mainly because Bootstrap's current Alpha CDN doesn't include Flexbox, which I'm sure they will in the future but for now I wanted to use it). Either way, it essentially accomplishes the same thing so I don't see why not to use a select box if that's what you want to do.

This current setup would allow someone to use Bootstrap version 2, but people should probably move forward from that, so I won't make that argument. Limiting the version is probably better for Grav themes anyway, and then if people want to use something else they can just do it without using this plugin.

**Comment by flaviocopes** [comment]
Yep, I think we can forget Bootstrap 2, just focusing on 3 and the upcoming 4 - if you then want to load a specific CSS file, you can still do it in a plugin or directly in the theme.

**Comment by ghost** [comment]
Ok, cool. Well now and have my first experience working on a Grav plugin so I'm satisfied. Sounds like nothing needs to change right now.

**Pull request closed without merging**
